### ISSUE TITLE
How to chain the 2 timers? 

### ISSUE THREAD

**Issue by M0stafaRady** [RTimothyEdwards/caravel_openframe_project#6]
I tried to add test for chaining the 2 timers but I can't figure out the right configuration for the registers.

**Comment by RTimothyEdwards** [comment]
It has been a while since I wrote that, but. . .

The "chained" configuration has both counters acting like a single 64-bit counter.  You need to set the "chained" configuration bit to 1 (bit 3, or value 8, in both counters).  Set the high counter first (timer 1), since it will not trigger until the low counter (timer 0) strobes it.  Testing is a bit tricky because the chained mode is designed for ultra-long counts.  But it should be sufficient to do something like set the high counter to 1, the low counter to a small number, do a one-shot down-count, run it a few cycles, and confirm that the low counter passed zero and rolled over, and that the high counter decremented to value zero.  That confirms that the registers are chained without specifically waiting for the entire count.

Other than setting the "chained" bit and making sure that the upper timer is set before the lower timer, otherwise it just acts like a regular counter.  Without looking closely at the code, I can't say for sure what happens if the two counters don't agree on the mode bits.

**Comment by M0stafaRady** [comment]
The high counter start decrementing when the low counter reached 0. but the low counter didn't rollover it stays at 0. 
![image](https://github.com/RTimothyEdwards/caravel_openframe_project/assets/107422726/39340145-aeb7-4238-8787-563d0926f21b)

here is the sequence I used 
```
    // chain
    timer1_chain(1);
    timer0_chain(1);
    // count down
    timer1_upcount(0);
    timer0_upcount(0);
    // one shot
    timer1_oneshot(1);
    timer0_oneshot(1);
    // enable
    timer1_enable(1);
    timer0_enable(1);
    // setting data
    timer1_data(0x1);
    timer0_data(0xF);
```
